services:
  libretv:
    build:
      context: https://github.com/l2340702/LibreTV.git
    container_name: libretv
    ports:
      - "8899:8080"
    environment:
      - PASSWORD=${PASSWORD:-your_password}
    restart: unless-stopped

#volumes:
#  libretv_data:
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: ${PWD:-.}/data # 可将 ${PWD:-.} 修改为你想要的路径，默认为当前目录下的 data 文件夹
